server:
  port: 9296

spring:
  application:
    name: TRADING-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JUKI-J/config-server.git
          clone-on-start: true